### PR TITLE
Dependency injection / Images

### PR DESCRIPTION
**Pull request by JBraunsmaJr**
# Breaking Database Change
Updated reminders to utilize ulongs as IDs. Granted, we do not use this feature much so it shouldn't be too much of an issue migrating

# Major Changes
Converted framework to utilize Dependency injection. The existing documentation on the DisCatSharp / DSharpPlus framework have invalid examples, or lack the documentation.

# Misc Changes
- Added data structures for the various configuration options, which also leverage DI framework
- Database lifetime has been updated to singleton scope
- Added Image service project which lays the groundwork for banner creation, or implementing random images for gamification purposes... or whatever we want
- Migrated to UnofficialDevryIT.Architecture package - which is why DevryApplication / DevryCore have been deleted

### CODE REVIEW

**Comment by tyates2020** [comment]
K

**Review by tyates2020 — APPROVED** [review]
K

**Comment by JBraunsmaJr** [comment]
Waiting for #18 to be completed, which will merge into this

**Comment by JBraunsmaJr** [comment]
@tyates2020 Was waiting for #18 to be completed before merging this into master

**Comment by JBraunsmaJr** [comment]
Creating a label to help indicating if a PR is not ready for merge yet

**Pull request merged**
